from typing import Protocol, Self


class AnamnesisMessageBuilderProtocol(Protocol):

    def add_diagnosis(self, diagnosis: str | None) -> Self: ...

    def add_blood_gas_ph(self, blood_gas_ph: float | None) -> Self: ...

    def add_blood_gas_co2(self, blood_gas_co2: float | None) -> Self: ...

    def add_blood_gas_glu(self, blood_gas_glu: float | None) -> Self: ...

    def add_blood_gas_lac(self, blood_gas_lac: float | None) -> Self: ...

    def add_blood_gas_be(self, blood_gas_be: float | None) -> Self: ...

    def build(self) -> str: ...
