services:
  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_su_password
      TZ: Europe/Moscow
    secrets:
      - pg_su_password
      - app_migrator_password
      - app_runtime_password
      - app_readonly_password
      - keycloak_db_password
    command:
      - "postgres"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: "5432"
      KC_DB_URL_DATABASE: woym_market
      KC_DB_SCHEMA: kc_auth
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD_FILE: /run/secrets/keycloak_db_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/keycloak_password
      KC_HEALTH_ENABLED: "true"
    secrets:
      - keycloak_db_password
    volumes:
      - ./keycloak/providers:/opt/keycloak/providers:ro
      - ./keycloak/themes:/opt/keycloak/themes:ro
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health/ready >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  server:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: run/app.Dockerfile
      args:
        POETRY_VERSION: 2.1.4
        VCS_REF: "abc123"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./logs:/backend/logs
    expose:
      - 8000
    ports:
      - "${HTTP_PORT}:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:${HTTP_PORT:-8000}/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

secrets:
  pg_su_password:         { file: secrets/pg_su_password }
  app_migrator_password:  { file: secrets/app_migrator_password }
  app_runtime_password:   { file: secrets/app_runtime_password }
  app_readonly_password:  { file: secrets/app_readonly_password }
  keycloak_db_password:   { file: secrets/keycloak_db_password }
  keycloak_password:      { file: secrets/keycloak_password }

volumes:
  db-data-dev: