services:
  server:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: run/app.Dockerfile
      args:
        POETRY_VERSION: 2.1.4
        VCS_REF: "abc123"
    env_file:
      - .env
    environment:
      RUN_MODE: ${RUN_MODE}
      EMULATOR_URI: ${EMULATOR_URI}

      HTTP_HOST: ${HTTP_HOST}
      HTTP_PORT: ${HTTP_PORT}
      API_VERSION: ${API_VERSION}
      DB_DRIVER: ${DB_DRIVER}
      DB_DATABASE_NAME: './../app.db'
    ports:
      - "8001:${HTTP_PORT}"

  emulator:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: run/emulator.Dockerfile
      args:
        POETRY_VERSION: 2.1.4
        VCS_REF: "abc123"

  external_db:
    restart: unless-stopped
    image: postgres:17.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: med_db
    volumes:
      - external-db-data-local:/var/lib/postgresql/data
    ports:
      - "5400:5432"

volumes:
  external-db-data-local:
